### ISSUE TITLE
Add support for reading HttpStatusCode and headers of response, not only deserialized model

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-network#118]
in our usecases we not read response headers yet and do status code checks only in ErrorFeature (if status code not successful then this feature try create exception for this case).
i think it will be good if we add `HttpResponse<Model>` case in generation, in addition to already exists methods

_Originally posted by @Alex009 in https://github.com/icerockdev/moko-network/issues/3#issuecomment-601499416_

**Comment by shadowsheep1** [comment]
Hi @Alex009 .  Any news about this?

**Comment by Alex009** [comment]
will be released in 0.21.0
