### ISSUE TITLE
Support header arguments in generated requests

### ISSUE THREAD

**Issue by nothingelsematters** [icerockdev/moko-network#141]
If there is a header parameter in `swagger.json`, then the gradle code generation plugin generates a code for the corresponding endpoint with a function argument of this header, but it does not add this header to a request.

Using openAPI generation directly you can face the same issue when using "kotlin-ktor-client" generator (there is no such bug using "kotlin" generator with "multiplatform" library, but this code seems to be outdated for new kotlin version).

The generated code looks like this:

```kotlin
override public suspend fun endpoint(authorization: kotlin.String) : Response {
    ...
    with(builder.headers) {
        append("Accept", "application/json")
    }
    ...
}
```

There is no usage of an "authorization" parameter in a function body.

**Comment by Alex009** [comment]
will be released in 0.18.0
