### ISSUE TITLE
Cannot generate public classes

### ISSUE THREAD

**Issue by shadowsheep1** [icerockdev/moko-network#22]
I've tried to set `nonPublicApi` to `false` as an additional property and a config option value (it should be and additional property for kotlin language) but classes have always `internal` visibility.

`nonPublicApi` is set to false by default, but I've tried to force it anyway.

```
openApiGenerate {
    // https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin
    println("--> openapi-generator <-")
    println("additionalProperties.size ${additionalProperties.get().entries.size}")
    println("--additional-properties nonPublicApi=true")
    inputSpec.set(file("src/swagger.json").path)
    //inputSpec.set(file("src/openapi.yaml").path)
    additionalProperties.set(mutableMapOf("nonPublicApi" to "false"))
    configOptions.set(mutableMapOf("nonPublicApi" to "false"))
    generatorName.set("kotlin-ktor-client")
    verbose.set(true)
    println("additionalProperties $additionalProperties")
    println("additionalProperties.size ${additionalProperties.get().entries.size}")
    println("--> openapi-generator <-")
}
```

`internal class PetApi(...`

**Comment by shadowsheep1** [comment]
I've found that your mustache templates have the a fixed `internal` visibility, it's not possible to change it by configurations or additional properties.

**Comment by Alex009** [comment]
hi!
yes, when we develop this templates we not research this option (`nonPublicApi`)...we will add support of this option in next releases. Also it will be helpful if you send pull request with fix from your templates

**Comment by shadowsheep1** [comment]
Hi @Alex009 ! Yup I could send you a pull request, but I'm not an expert in custom gradle plugin and It seems to me that this project setup of this repo uses the published versione of the plugin and not the local one. Am I right? Before doing a PR I'd like to test it first, without adding custom mustache templates in the sample project.

**Comment by Alex009** [comment]
please use instructions from readme - https://github.com/icerockdev/moko-network#set-up-locally
we use mavenLocal for testing purpose
