### ISSUE TITLE
NullPointerException when trying parse date in not same format

### ISSUE THREAD

**Issue by DevTchernov** [icerockdev/moko-network#32]
Caused by force cast:
https://github.com/icerockdev/moko-network/blob/master/network/src/iosMain/kotlin/dev/icerock/moko/network/GMTDateExt.kt#L20

**Comment by Alex009** [comment]
@DevTchernov what behaviour is expected in this case? passed format not correct, so if we throw some `IllegalFormatException` - it will be expected?

**Comment by Alex009** [comment]
will be in 0.11.0
