### ISSUE TITLE
Date transformer make crash with incorrect format

### ISSUE THREAD

**Issue by kovalandrew** [icerockdev/moko-network#38]
There are two expect methods for GMTDate:

```
expect fun String.toDate(format: String): GMTDate
expect fun GMTDate.toString(format: String): String
```

Both of them have non-optional result. On iOS side there is cruel force unwrap here:

`val date: NSDate = formatter.dateFromString(this)!!`

It will provide crash any time, when format of provided string argument not match format of current string.
i.e. try to parse string "13.12.2020" with format "dd.MM.YYYY'T'mm:ss". Maybe it would be better to make it optional? I really don't want crashes if backend change some symbols =(

**Comment by Alex009** [comment]
same as #32 and also throw exception is correct behavior. if you want just got null - do `runCatching {}. getOrNull()`.
later forcecast will be changed to `DateFormatException` but it should be throw of exception, not `null value`
