### ISSUE TITLE
Generate multiple APIs on the same module

### ISSUE THREAD

**Issue by Jaime97** [icerockdev/moko-network#39]
I'm trying to generate classes from two different API specifications but it seems that I can only use `openApiGenerate` once for every module.

I've also found [this](https://github.com/icerockdev/moko-template/issues/5) issue in moko template, in which the same problem was reported a while ago. Has this been fixed? Is there any workaround now?

**Comment by Alex009** [comment]
for now workaround - multiple modules with api. later we add support of one module

**Comment by Jaime97** [comment]
Okey, I will use the workaround until then.

**Comment by Alex009** [comment]
implemented support out of box in #45
