### ISSUE TITLE
Can't manage 400 response

### ISSUE THREAD

**Issue by Jaime97** [icerockdev/moko-network#40]
I have an Api definition with this responses defined:
```
responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MyData'
        '400':
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest' 
```

Everything works fine when I execute the `openApiGenerate` task but the generated Api class ends up doing something like this to manage results :
```
try {
      //not primitive type
      val result: String = _httpClient.request(builder)
      return _json.decodeFromString(MyData.serializer().let { ListSerializer(it) }, result)
} catch (pipeline: ReceivePipelineException) {
      throw pipeline.cause
}
```
This works fine if the result is suscessfull but if I get a BadRequest then it crash at the line ` _json.decodeFromString(MyData.serializer().let { ListSerializer(it) }, result)`.

Although my  `BadRequest` class is generated, it is not used anywhere so, how are the errors managed?

**Comment by Dorofeev** [comment]
For processing errors you can use [ExceptionFeature](https://github.com/icerockdev/moko-network/blob/master/network/src/commonMain/kotlin/dev/icerock/moko/network/features/ExceptionFeature.kt) for ktor HttpClient

Here example of configuring HttpClient with ExceptionFeature
```
HttpClient {
            install(ExceptionFeature) {
                exceptionFactory = HttpExceptionFactory(
                    defaultParser = ErrorExceptionParser(json),
                    customParsers = mapOf(
                        HttpStatusCode.UnprocessableEntity.value to ValidationExceptionParser(json)
                    )
                )
            }
            
            // disable standard BadResponseStatus - exceptionfactory do it for us
            expectSuccess = false
        }
```
I don't think [ErrorExceptionParser](https://github.com/icerockdev/moko-network/blob/master/network/src/commonMain/kotlin/dev/icerock/moko/network/exceptionfactory/parser/ErrorExceptionParser.kt) will work for you, but you can create your custom parser for error. Also you can use generated `BadRequest` class serializer inside your custom error parser.

**Comment by Jaime97** [comment]
@Dorofeev Could you provide any example or documentation on how to do that?

**Comment by Dorofeev** [comment]
[Here](https://github.com/Dorofeev/moko-network/blob/exception-feature-sample/sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/TestViewModel.kt) you can find sample of using `ExceptionFeature` 
And [here](https://github.com/Dorofeev/moko-network/blob/exception-feature-sample/sample/mpp-library/src/commonMain/kotlin/com/icerockdev/library/CustomExceptionParser.kt) is implementation of custom exception parser. `BadResponse` class was generated from swagger.json
Function `onCallError` calls request that always failed, and error response will be parsed by `CustomExceptionParser`

**Comment by Jaime97** [comment]
@Dorofeev sorry for the delay, thanks for the examples, I was able to implement it now 👍
