### ISSUE TITLE
Ktor 1.5.0 support

### ISSUE THREAD

**Issue by cl3m** [icerockdev/moko-network#42]
This library does not build on iOS and break with the error kotlinx.serialization.json/Json|null[0] is not found like https://github.com/Kotlin/kotlinx.serialization/issues/1110

Could you update your library to the latest ktor, serialization, coroutines and kotlin versions ?

Thank you

**Comment by Alex009** [comment]
are ktor 1.5.0 stable enough on iOS? all ktor client upper than 1.4.0 on our projects was unusable at all and it block us from update moko-network

**Comment by cl3m** [comment]
I've no problem with ktor 1.5.0 yet. I've removed the moko-network dependancy and use only the generated classes and it works so far.

**Comment by xsveda** [comment]
Since `coroutines-1.4.2-native-mt` Ktor works fine, we have Ktor `1.5` on two projects already with no issue so far.

**Comment by Alex009** [comment]
for us [this issue](https://youtrack.jetbrains.com/issue/KTOR-1087#focus=Comments-27-4600176.0-0) can be blocker.
i add issue to 0.10.0 version. we can't not update ktor at all, so update needed. but how communicate with ktor-features if they freeze own configuration - opened question.
for example in moko-network TokenFeature can broke cause this.

**Comment by Alex009** [comment]
maybe help https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native.concurrent/-worker-bound-reference/

**Comment by Alex009** [comment]
will be available in 0.11.0

**Comment by dalewking** [comment]
Trying to upgrade to 0.11.0 and have a similar issue:

> Task :wfmShared:linkReleaseFrameworkIosArm64 FAILED
e: Compilation failed: Deserializer for declaration public kotlinx.serialization.builtins/serializer|3609691864716130699[0] is not found

 * Source files: 
 * Compiler version info: Konan: 1.4.31 / Kotlin: 1.4.31
 * Output kind: FRAMEWORK

e: java.lang.IllegalStateException: Deserializer for declaration public kotlinx.serialization.builtins/serializer|3609691864716130699[0] is not found

**Comment by Alex009** [comment]
@dalewking please run `./gradlew dependencies` and paste result here

**Comment by dalewking** [comment]
I seem to have resolved it. I had kotlinx-serialization-core set to version 1.0.1
