### ISSUE TITLE
Generates incorrect code for array parameter with uniqueItems set to true

### ISSUE THREAD

**Issue by dalewking** [icerockdev/moko-network#92]
We have a parameter defined as follows where it takes a set of UUIDs:
 
        {
          "name" : "timeOffRequestIds",
          "in" : "body",
          "required" : true,
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string",
              "format" : "uuid"
            },
            "uniqueItems" : true
          }
        }
        
 The parameter to the API is declared as a Set due to the uniqueItems:
 
     timeOffRequestIds: kotlin.collections.Set<kotlin.String>

But the code to serialize is trying to use `ListSerializer`:

     _json.encodeToString(ListSerializer(kotlin.String.serializer()), timeOffRequestIds)

That should be using `SetSerializer`, not `ListSerializer`

**Comment by Alex009** [comment]
will be available in 0.11.0
